version: '3'

services:
  web_golang_gin:
    container_name: 'web_golang_gin'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    volumes:
      - .:/usr/src/app
      - ./files/entrypoint.sh:/usr/local/bin/entrypoint.sh
    networks:
      - golang_gin

networks:
  golang_gin:
    driver: bridge