version: '3'

services:
  web_golang_gin:
    container_name: 'web_golang_gin'
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - golang_gin

networks:
  golang_gin:
    driver: bridge